name: fast_tech_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_animations: "^1.0.0"
  shared_preferences: ^2.0.15
  lottie: ^1.3.0
  package_info:
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  auto_size_text: ^3.0.0
  dio: ^4.0.6
  cached_network_image:
  flutter_easyrefresh: ^2.2.1
  awesome_dialog: ^2.2.1
  carousel_slider: ^4.1.1
  bottom_sheet: ^3.0.0
  device_info: ^2.0.3
  flutter_polyline_points: ^1.0.0
  uuid: ^3.0.6
  flutter_colorpicker: ^1.0.3
  image_picker:
  file_picker:
  flutter_svg: ^1.0.0
  multi_image_picker2: ^5.0.2
  flutter_local_notifications: ^9.0.3
  html: 
  flutter_html: 

#  *** Firebase ***
  # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets
  # you reliably deliver messages on Android and iOS.
  firebase_messaging: 11.2.6
  firebase_messaging_platform_interface: 3.1.6
  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization and offline support
  cloud_firestore: 3.1.8
  cloud_firestore_platform_interface: 5.4.13

  firebase_core: ^1.19.1


  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/i18n/
    - assets/images/
    - assets/lottie/
    - assets/svg/


  uses-material-design: true


